# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See:
# If false, merge configs from `_data/next.yml` into default configuration (rewrite).
# If true, will fully override default configuration by options from `_data/next.yml` (override). Only for NexT settings.
# And if true, all config from default NexT `_config.yml` have to be copied into `next.yml`. Use if you know what you are doing.
# Useful if you want to comment some options from NexT `_config.yml` by `next.yml` without editing default config.
# ---------------------------------------------------------------

override: false


# =================================================================
# =================================================================
# ===                      全局变量设置                          ===
# =================================================================
# =================================================================

head: 
  keywords: Sitio | hexo-theme-sitio | Sitio 主题
  description: Sitio是基于hexo写的一款主题，这里有最好看的主题，欢迎您的使用和我们一起来开发这款主题。
  narmal: /icon/favicon.ico
  theme_color: '#fff'
  # manifest: /manifest.json
  author: aftersoil


# 收录，[google baidu bing yandex qihu]等收录代码
Included: 
  google_site_verification: 
  baidu_site_verification: 
  bing_site_verification: 
  yandex_site_verification: 
  qihu_site_verification: 


# 个人资料
Profile:
  name: 
  avatar: 


# 内部主题选择
theme: 
  concise: true
  pretty: false
  customize: false

# =================================================================
# =================================================================
# ===                     简洁版全局变量                         ===
# =================================================================
# =================================================================








# =================================================================
# =================================================================
# ===                     漂亮版全局变量                         ===
# =================================================================
# =================================================================






# =================================================================
# =================================================================
# ===                       其它变量配置                         ===
# =================================================================
# =================================================================

# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css: 
  js: 
    jquery: /libs/jquery/jquery.min.js


itemscope: theme
itemtype: http://schema.org/WebPage


# Assets
css: css
js: js
images: images

version: 1.0.1
